/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProblemsRouteImport } from './routes/problems'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DiscussRouteImport } from './routes/discuss'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContestRouteImport } from './routes/contest'
import { Route as CompanyAssessmentRouteImport } from './routes/company-assessment'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProblemsIndexRouteImport } from './routes/problems.index'
import { Route as ProblemsProblemIdRouteImport } from './routes/problems.$problemId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsRoute = ProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscussRoute = DiscussRouteImport.update({
  id: '/discuss',
  path: '/discuss',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestRoute = ContestRouteImport.update({
  id: '/contest',
  path: '/contest',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyAssessmentRoute = CompanyAssessmentRouteImport.update({
  id: '/company-assessment',
  path: '/company-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsIndexRoute = ProblemsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProblemsRoute,
} as any)
const ProblemsProblemIdRoute = ProblemsProblemIdRouteImport.update({
  id: '/$problemId',
  path: '/$problemId',
  getParentRoute: () => ProblemsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/company-assessment': typeof CompanyAssessmentRoute
  '/contest': typeof ContestRoute
  '/dashboard': typeof DashboardRoute
  '/discuss': typeof DiscussRoute
  '/login': typeof LoginRoute
  '/problems': typeof ProblemsRouteWithChildren
  '/register': typeof RegisterRoute
  '/problems/$problemId': typeof ProblemsProblemIdRoute
  '/problems/': typeof ProblemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/company-assessment': typeof CompanyAssessmentRoute
  '/contest': typeof ContestRoute
  '/dashboard': typeof DashboardRoute
  '/discuss': typeof DiscussRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/problems/$problemId': typeof ProblemsProblemIdRoute
  '/problems': typeof ProblemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/company-assessment': typeof CompanyAssessmentRoute
  '/contest': typeof ContestRoute
  '/dashboard': typeof DashboardRoute
  '/discuss': typeof DiscussRoute
  '/login': typeof LoginRoute
  '/problems': typeof ProblemsRouteWithChildren
  '/register': typeof RegisterRoute
  '/problems/$problemId': typeof ProblemsProblemIdRoute
  '/problems/': typeof ProblemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/company-assessment'
    | '/contest'
    | '/dashboard'
    | '/discuss'
    | '/login'
    | '/problems'
    | '/register'
    | '/problems/$problemId'
    | '/problems/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/company-assessment'
    | '/contest'
    | '/dashboard'
    | '/discuss'
    | '/login'
    | '/register'
    | '/problems/$problemId'
    | '/problems'
  id:
    | '__root__'
    | '/'
    | '/company-assessment'
    | '/contest'
    | '/dashboard'
    | '/discuss'
    | '/login'
    | '/problems'
    | '/register'
    | '/problems/$problemId'
    | '/problems/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanyAssessmentRoute: typeof CompanyAssessmentRoute
  ContestRoute: typeof ContestRoute
  DashboardRoute: typeof DashboardRoute
  DiscussRoute: typeof DiscussRoute
  LoginRoute: typeof LoginRoute
  ProblemsRoute: typeof ProblemsRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems': {
      id: '/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof ProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discuss': {
      id: '/discuss'
      path: '/discuss'
      fullPath: '/discuss'
      preLoaderRoute: typeof DiscussRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contest': {
      id: '/contest'
      path: '/contest'
      fullPath: '/contest'
      preLoaderRoute: typeof ContestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-assessment': {
      id: '/company-assessment'
      path: '/company-assessment'
      fullPath: '/company-assessment'
      preLoaderRoute: typeof CompanyAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/': {
      id: '/problems/'
      path: '/'
      fullPath: '/problems/'
      preLoaderRoute: typeof ProblemsIndexRouteImport
      parentRoute: typeof ProblemsRoute
    }
    '/problems/$problemId': {
      id: '/problems/$problemId'
      path: '/$problemId'
      fullPath: '/problems/$problemId'
      preLoaderRoute: typeof ProblemsProblemIdRouteImport
      parentRoute: typeof ProblemsRoute
    }
  }
}

interface ProblemsRouteChildren {
  ProblemsProblemIdRoute: typeof ProblemsProblemIdRoute
  ProblemsIndexRoute: typeof ProblemsIndexRoute
}

const ProblemsRouteChildren: ProblemsRouteChildren = {
  ProblemsProblemIdRoute: ProblemsProblemIdRoute,
  ProblemsIndexRoute: ProblemsIndexRoute,
}

const ProblemsRouteWithChildren = ProblemsRoute._addFileChildren(
  ProblemsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanyAssessmentRoute: CompanyAssessmentRoute,
  ContestRoute: ContestRoute,
  DashboardRoute: DashboardRoute,
  DiscussRoute: DiscussRoute,
  LoginRoute: LoginRoute,
  ProblemsRoute: ProblemsRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
